# Generated by Django 5.2.6 on 2026-03-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_anggota/'),
        ),
    ]
