# Generated by Django 6.0.3 on 2026-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_alter_anggota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
