# Generated by Django 5.2.6 on 2026-04-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_alter_anggota_id 2'),
        ('biodata', '0003_alter_anggota_id'),
    ]

    operations = [
    ]
